import { ChatGPTUnofficialProxyAPI } from 'chatgpt'

export async function example() {

    

    const api = new ChatGPTUnofficialProxyAPI({
    accessToken: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJlYWJlbDQxMjlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdlb2lwX2NvdW50cnkiOiJCTyJ9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsidXNlcl9pZCI6InVzZXItb2FlMUJxUkNBOE1FUndvQ1FzdUc3SHdQIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNDcwODI0MTM5ODMyMDg3NzM4MSIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NzcxMzIyNDQsImV4cCI6MTY3ODM0MTg0NCwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.fPkldt9hVLENwrpjY8DKexUz6JhR7W6k_oPifeMnnteuSaa8OUTes_Sn2h7L_Ws7GqjTc84oQzrW2zwk62GRXOefBmao4HVUV4RzNdorzc7pi9CMhAs3bRwbe14Ts-sv2AMcIn2AdBKpPg7xbkPpgKdYuEcxDA7a_OX9ksxaCHFjC4thmXYwMQg1mXOfFTDUVNmpfS0Ma6tPWk23IN-56hDzh3iqXK9awgq_GFvVaX0oWYwhLUEBD16lVRvBMvYloVgsvY1sgbOjsS_OcQgkUOntm-K2DVjTr4Pivux8QcCLhwGF0byYDY_IQxFCTeyN1l0c2AZ3eWHS-X1bbyLPrA",
    debug: true,
    })
  
    const res = await api.sendMessage('creame un contrato de union de 2 empresas, una llamada abogacy.io y la otra logitech.com')
    console.log(res.text)
  }
  
  